name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    name: Lint (Shellcheck)
    uses: ./.github/workflows/lint.yaml

  format:
    name: Format (shmft)
    needs: lint
    uses: ./.github/workflows/format.yaml

  pipeline_completion:
    name: Pipeline Completion
    runs-on: ubuntu-latest
    if: always()
    needs:
      - lint
      - format
    steps:
      - name: Pipeline succeeded
        uses: re-actors/alls-green@release/v1
        with:
        jobs: ${{ toJSON(needs) }}
